include: package:lint/analysis_options.yaml

linter:
  rules:
    parameter_assignments: true
    avoid_function_literals_in_foreach_calls: false
    constant_identifier_names: false
    avoid_print: false
    file_names: false

analyzer:
  errors:
    missing_required_param: error
    parameter_assignments: error
    missing_return: error